export const cityMap = {
  서울: "Seoul",
  부산: "Busan",
  대구: "Daegu",
  인천: "Incheon",
  광주: "Gwangju",
  대전: "Daejeon",
  울산: "Ulsan",
  수원: "Suwon",
  용인: "Yongin",
  청주: "Cheongju",
  전주: "Jeonju",
  안산: "Ansan",
  평택: "Pyeongtaek",
  천안: "Cheonan",
  김해: "Gimhae",
  포항: "Pohang",
  창원: "Changwon",
  경주: "Gyeongju",
  춘천: "Chuncheon",
  원주: "Wonju",
  강릉: "Gangneung",
  여수: "Yeosu",
  순천: "Suncheon",
};
